spring:
  profiles: dev
application:
  current-profile: dev
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level: 
    com:
      netflix:
        hereka: false
        discovery: false