spring:
  profiles: dev
server:
  port: 9190
application:
  current-profile: dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
