server:
  port: 9002
application:
  current-profile: dev
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/geoimmo_promotiondb
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        default_schema: geoimmo
    generate-ddl: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
